### ISSUE TITLE
it there any benchmarks?

### ISSUE THREAD

**Issue by benlee73** [AyanGadpal/Document-Image-Augmentation#1]
Thanks for the good code.
When applying this to an image dataset, was there any performance improvement over before applying it?
Do you have any benchmarks?

**Comment by AyanGadpal** [comment]
Yes, We do have benchmarks for Smudge and Dilation Augmentations, Please find it in our [CascadeTabNet Paper ](https://openaccess.thecvf.com/content_CVPRW_2020/papers/w34/Prasad_CascadeTabNet_An_Approach_for_End_to_End_Table_Detection_and_CVPRW_2020_paper.pdf) Table 1
